### ISSUE TITLE
Not able to bypass "Require Approvals" branch protection rule

### ISSUE THREAD

**Issue by diegocam** [gr2m/merge-schedule-action#100]
When this Github action kicks in, it tries to merge the PR. However when it tries to merge onto `develop` it is stopped as I have a rule set that for that branch we need to have at least 1 reviewer approve the PR, as it is normally the case with any other PRs that will be merged onto develop. 

This is the comment that gets posted on the PR whenever this happens:

<img width="952" alt="Screenshot 2024-07-24 at 10 27 10 AM" src="https://github.com/user-attachments/assets/77818d49-763b-4b50-b3fd-05e951cb6c4c">

That branch protection rule setting is here:
<img width="808" alt="Screenshot 2024-07-24 at 10 28 37 AM" src="https://github.com/user-attachments/assets/70d01716-5e10-4bb9-ad65-69c2bf0b04d6">

and this is my workflow yml:
```yml
name: Merge Schedule to Develop

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
  schedule:
    - cron: "*/5 * * * *"

jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/merge-schedule-action@v2
        with:
          merge_method: squash
          require_statuses_success: "true"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Is there a way to bypass this setting?
