### ISSUE TITLE
invalid `cron` attribute "0 * * * 4-7"

### ISSUE THREAD

**Issue by beto-aveiga** [gr2m/merge-schedule-action#101]
I have the following workflow:

```
name: Merge Schedule

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
  schedule:
    - cron: '0 * * * 4-7'

jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/merge-schedule-action@v2
        with:
          time_zone: 'America/Los_Angeles'
          require_statuses_success: 'true'
          automerge_fail_label: 'automerge-fail'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

![image](https://github.com/user-attachments/assets/33bd4917-6820-497e-b6b8-fc5837156822)

What am I doing wrong?
Is there a way I can overcome this issue with the actual version of this action?
Maybe using multiple cron configs?

Many thanks! :)
