### ISSUE TITLE
feature request: set status to "success" before merging

### ISSUE THREAD

**Issue by hmble** [gr2m/merge-schedule-action#16]
here is my workflow file for reference

```yaml
name: Merge Schedule
env:
  TZ: Asia/Kolkata
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
  schedule:
    # https://crontab.guru/every-hour
    - cron: "*/5 * * * *"

jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/merge-schedule-action@v1.1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Maybe we need to update github check run to completed after merging PR [after this line](https://github.com/gr2m/merge-schedule-action/blob/68988f073e26ba2dcc74830c4c0cb99c745d5d98/lib/handle_schedule.js#L56) I don't know much about github action so this is a possible guess. I hope its right.

![2020-08-16-223040_905x230_scrot](https://user-images.githubusercontent.com/16825207/90339679-de7bad80-e00f-11ea-8075-ea9c7ae5f8ea.png)
