### ISSUE TITLE
Warning: Unexpected input(s) 'time_zone', valid inputs are ['merge_method']

### ISSUE THREAD

**Issue by polevaultweb** [gr2m/merge-schedule-action#30]
When running the action with this merge-schedule.yml file

```
name: Merge Schedule
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
  schedule:
    # https://crontab.guru/every-hour
    - cron: 0 * * * *

jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/merge-schedule-action@v1.2.4
        with:
          # Merge method to use. Possible values are merge, squash or
          # rebase. Default is merge.
          merge_method: merge
          time_zone: "UTC"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

I see 'Warning: Unexpected input(s) 'time_zone', valid inputs are ['merge_method']' in the output

![image](https://user-images.githubusercontent.com/1770201/100239856-cf1ed100-2f29-11eb-8fc7-7f6d3ba95134.png)
