### ISSUE TITLE
Merge Not Completing

### ISSUE THREAD

**Issue by bcox24** [gr2m/merge-schedule-action#39]
This issue probably isn't so much an issue in the code as it is with the documentation (or my understanding of GitHub Actions), not sure, GitHub Actions still confuse me. 

I have a .github/workflow/merge-schedule.yml file with the contents of: 

```
name: Merge Schedule
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
  schedule:
    # https://crontab.guru/every-hour
    - cron: 0 * * * *

jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/merge-schedule-action@v1
        with:
          # Merge method to use. Possible values are merge, squash or
          # rebase. Default is merge.
          merge_method: merge
          #  Time zone to use. Default is UTC.
          time_zone: "America/Phoenix"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

```

So, it's almost identical to the example given. 

Then, in the description of the PR I'll put something like `/schedule 2021-04-07T10:00:00.000`. The output shows `Schedule date found` and `Check run created` however the merge doesn't happen at the expected schedule time. 

What am I missing? 

Are the cron in the action and schedule in the description mutually exclusive? We require code reviews, and the PR is approved and ready to be merged, but is that process throwing this off somehow? Am I missing a pull request type? Did it actually attempt the merge? It seems like it is still waiting. Are there more logs I can view somewhere? 

Sorry about creating an issue, but wasn't sure how else to get my basic questions answered. Thanks!

**Comment by gr2m** [comment]
The action is run once per hour. It checks if the scheduled time is in the past, and if it is, it attempts to merge. The `/schedule` command does not create an explicit run of that action at the given time.

You can see logs in the `actions` tab of the repository

**Comment by franciscocobas** [comment]
When does the cron job suppose to run? 
In the date that we write in this line
```
schedule:
  - cron: `59 * * * *`
 ```
or the line we write in the description?
`/schedule 2021-05-01`

**Comment by gr2m** [comment]
> When does the cron job suppose to run?
> In the date that we write in this line
> 
> ```
> schedule:
>   - cron: `59 * * * *`
> ```
> 
> or in the line that we write in the description?
> `/schedule 2021-05-01`

`59 * * * *` should run the cron job once per hour, check your actions tab to see if that is happening. The first time it runs on May 1st (UTC), the PR will be merged.

**Comment by moringaman** [comment]
This action is not working at all for me, my yml file is as follows;

```
name: Merge Schedule
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
  schedule:
    # https://crontab.guru/every-hour
    - cron: 1 * * * *

jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/merge-schedule-action@v1.3.0
        with:
          # Merge method to use. Possible values are merge, squash or
          # rebase. Default is merge.
          merge_method: squash
          #  Time zone to use. Default is UTC.
          time_zone: "Europe/London"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

and I have '/schedule 2021-08-14T10:10:04.000' in the pull request description but the job just sticks on 'In progress — Scheduled to be merged on 2021...' the time passes but the pull request is never merged.

**Comment by gr2m** [comment]
can you share the repository if it's public? If it's not, can you please create a public repository that replicates the same behavior? I cannot help you otherwise

**Comment by moringaman** [comment]
Hi, the pull request on my repo where I was trying to use the action is here 

https://github.com/moringaman/auto-merge-test/pull/3

I have subsequently tried with other actions that do similar things but without success

**Comment by gr2m** [comment]
can you run the `gr2m/merge-schedule-action` action on a schedule? You seem to be using a different action

**Comment by moringaman** [comment]
@gr2m please take a look at this pull request and let me know why it didn't merge on schedule if possible

https://github.com/moringaman/automerge/pull/10

Thanks

**Comment by gr2m** [comment]
Did you remove the workflow files form the repository?

The actions tab does not show any runs triggered by the schedule:
https://github.com/moringaman/automerge/actions

If the workflow is not triggered by it's `cron.schedule` configuration, then no pull request will be merged.

**Comment by moringaman** [comment]
I'm not sure I understand your response it can be seen from the action that the merge is pending, it's just that it does not run. The workflow files where not removed though as if you look they are still there see the link below

https://snippets.cacher.io/snippet/1ffd2538b47755f56a77

**Comment by gr2m** [comment]
The `gr2m/merge-schedule-action` has two parts

```yml
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
  schedule:
    # https://crontab.guru/every-hour
    - cron: 0 * * * *
```

The first part is triggered by pull request events, that's what you see. The action recognized the `/schedule ...` string and set a pending status. But it will not merge unless the 2nd trigger (`schedule`) is not working. Which it does not in your case. And the reason is that the `.github/workflows/merge-schedule.yml` file has to be in your repository's default branch, otherwise the `schedule` event is not triggered. So merge the pull request at https://github.com/moringaman/automerge/pull/10, then try again.

Let me know if that works
