### ISSUE TITLE
Pull Request Never Merges

### ISSUE THREAD

**Issue by moringaman** [gr2m/merge-schedule-action#48]
This action is not working at all for me, my yml file is as follows;

```
name: Merge Schedule
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
  schedule:
    # https://crontab.guru/every-hour
    - cron: 1 * * * *

jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/merge-schedule-action@v1.3.0
        with:
          # Merge method to use. Possible values are merge, squash or
          # rebase. Default is merge.
          merge_method: squash
          #  Time zone to use. Default is UTC.
          time_zone: "Europe/London"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

and I have '/schedule 2021-08-14T10:10:04.000' in the pull request description but the job just sticks on 'In progress — Scheduled to be merged on 2021...' the time passes but the pull request is never merged.

Please can someone point me in the right direction?
