### ISSUE TITLE
HttpError: Invalid app_id

### ISSUE THREAD

**Issue by bellons91** [gr2m/merge-schedule-action#55]
I'm running this action on my **private** repository.

**My PRs get merged correctly**, but the action fails with this error:

> HttpError: Invalid app_id `13473` - check run can only be modified by the GitHub App that created it.

The YAML file I use for this action is almost the default one:

```yml

name: Merge Schedule
on:
  pull_request:
    types:
      - opened
      - edited
  schedule:
    # https://crontab.guru/every-hour
    - cron: 0 8 * * Tue

jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/merge-schedule-action@v1
        with: 
          merge_method: squash 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Any ideas for that?
