### ISSUE TITLE
PR not merged ?

### ISSUE THREAD

**Issue by cryptobench** [gr2m/merge-schedule-action#66]
Hi! First time trying this wonderful extension.

I've added **/schedule 2022-06-15T15:43:50+0200** to my PR, and it seems that the extension understood it , but it has not merged it yet. What am I doing wrong?

<img width="968" alt="image" src="https://user-images.githubusercontent.com/33448819/173842758-df7b978c-e25a-4188-b51b-761ab56a8349.png">

Here's my workflow:

```
name: Merge Schedule

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/merge-schedule-action@v2
        with:
          # Merge method to use. Possible values are merge, squash or
          # rebase. Default is merge.
          merge_method: merge
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
```

**Comment by gr2m** [comment]
You need to add a schedule trigger, next to `pull_request:`, e.g. 

```yml
  schedule:
    # https://crontab.guru/every-hour
    - cron: '0 * * * *'
```

See https://github.com/gr2m/merge-schedule-action/#usage

**Comment by yurith-rubio** [comment]
Hi Gregor;

I have been trying to use the action merge-schedule-action@v2 for a while but I just cannot get how it works. I got it to work a few times but others it does not work. I am testing changing the date and using the different file actions I have found.

Questions:
1. For this to work, should I ONLY add the file merge-schedule-action@v2 inside .github/workflows folders on my project files? or should I also add the other files you have on the zip file with the latest version (e.g. package.json).
2. Is this code correct? with the message on the description of the pull request: '/schedule'. If yes, what am I doing wrong?

`name: Merge Schedule

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
  schedule:
    # https://crontab.guru/every-minute
    - cron: '35 7 1 7 *'

jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/merge-schedule-action@v2
        with:
          # Merge method to use. Possible values are merge, squash or
          # rebase. Default is merge.
          merge_method: squash
          # Time zone to use. Default is UTC.
          time_zone: 'Europe/Berlin'
          # Require all pull request statuses to be successful before
          # merging. Default is `false`.
          require_statuses_success: 'true'
          # Label to apply to the pull request if the merge fails. Default is
          # `automerge-fail`.
          automerge_fail_label: 'merge-schedule-failed'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
`

I tried to first make different test, read the previous issues, change dates, but I am still having troubles. Hope you have some time to help me. Thank you in advance.

**Comment by misilot** [comment]
Sorry to hijack, but just want to make sure I understand.

The schedule needs to be defined, and if I set a very specific time in the PR using `/schedule YYYY-MM-DD:HH:MM:SS`, it won't run at that specific time (unless the cron matched it exactly), but at the next time the schedule is triggered (catching up any that might have been scheduled between schedule runs?

**Comment by gr2m** [comment]
correct.

**Comment by gr2m** [comment]
It might be worth to make it more clear how this action works in the README? PRs welcome

**Comment by misilot** [comment]
I am trying with the following (which is really almost a copy paste from the Readme): https://github.com/kstatelibrariesit/status.its.lib.k-state.edu/blob/main/.github/workflows/merge-schedule.yml

However, it doesn't seem to get scheduled or merged? Am I missing a step to have it recognize the schedule command in https://github.com/kstatelibrariesit/status.its.lib.k-state.edu/pull/4#issuecomment-1195620471 ?

Thanks!

**Comment by codesnail21** [comment]
![Screenshot_2022-07-28-08-06-42-95_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://user-images.githubusercontent.com/87218847/181408307-c53aac94-86d2-421e-94a5-496a601f9368.jpg)

PR is not merging at all 

?

**Comment by codesnail21** [comment]
![Screenshot_2022-07-28-08-06-42-95_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://user-images.githubusercontent.com/87218847/181408307-c53aac94-86d2-421e-94a5-496a601f9368.jpg)

PR is not merging at all 

? 

- does it work on private repo 

- all checks are passing but, merge is not being performed 

- is it because of I'm not using v2 ?

**Comment by rizypb** [comment]
Same issue I am encountering and PR is not being merged automatically

**Comment by ConorSheehan1** [comment]
Same issue, waited 2 hours after scheduled time but PR never merged. Does the workflow have to be in main branch already?

![Screenshot_20220904-200817](https://user-images.githubusercontent.com/16896053/188329722-d2f3f0c0-f1ae-4e45-806b-a90214701fd6.jpg)


```yaml
# https://github.com/marketplace/actions/merge-schedule
# https://github.com/gr2m/merge-schedule-action
name: Merge Schedule

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
  schedule:
    # https://crontab.guru/every-hour
    - cron: "0 * * * *"

jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/merge-schedule-action@v2
        with:
          # Merge method to use. Possible values are merge, squash or
          # rebase. Default is merge.
          merge_method: squash
          # Time zone to use. Default is UTC.
          # time_zone: 'America/Los_Angeles'
          # Require all pull request statuses to be successful before
          # merging. Default is `false`.
          require_statuses_success: "true"
          # Label to apply to the pull request if the merge fails. Default is
          # `automerge-fail`.
          automerge_fail_label: "merge-schedule-failed"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
