### ISSUE TITLE
time_zone question

### ISSUE THREAD

**Issue by victoriacheng15** [gr2m/merge-schedule-action#77]
What time zone name to use? Are you following this [list](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)? 

I set time zone and then typed `/schedule` with specific date in the PR. The bot still says it will merge at midnight UTC time, not the time from cron schedule. Did I use the wrong name for time zone? 

![image](https://user-images.githubusercontent.com/35031228/200202099-7b76067b-19b1-4b31-aab3-7b6413d77fe0.png)

```yml
on:
  pull_request:
    types: [opened, edited]
  schedule:
    # check https://crontab.guru/ for set up time
    - cron: "30 8 * * *"

jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Merge Schedule
        uses: gr2m/merge-schedule-action@v2.4.1
        with:
          merge_method: squash
          time_zone: "America/Edmonton"
          require_statuses_success: "true"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
