### ISSUE TITLE
Always merges, regardless of date/time set

### ISSUE THREAD

**Issue by 5starkarma** [gr2m/merge-schedule-action#83]
I have the job set to merge at 10AM UTC and I schedule it for days in the future, but it always instantly merges..

```
name: Merge to Master Scheduled Task

on:
  workflow_run:
    workflows: ["Build and Test"]
    types: [completed]
  schedule:
    - cron: 0 10 * * *

jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/development' && github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: gr2m/merge-schedule-action@v2
        with:
          automerge_fail_label: 'merge-schedule-failed'
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
```
