### ISSUE TITLE
How to work with branch protections?

### ISSUE THREAD

**Issue by jsodeman** [gr2m/merge-schedule-action#87]
We have branch protections set up that require that a PR be approved by another user before it can be merged. I scheduled a PR merge to that branch and the run resulted in this error:

> Scheduled merge failed: You're not authorized to push to this branch. Visit https://docs.github.com/articles/about-protected-branches/ for more information.

The PR has been approved, is there something that I need to adjust?

My action is

```yaml
name: Merge Schedule

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
  schedule:
    - cron: '0 * * * *'

jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/merge-schedule-action@v2
        with:
          merge_method: merge
          automerge_fail_label: 'automerge-fail'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
