### ISSUE TITLE
Can't get a simple config to work

### ISSUE THREAD

**Issue by birkasecorba** [gr2m/merge-schedule-action#92]
Here is my config, and below that I've provided all the test diffs I tried. Any help is appreciated:
```yml
name: Merge Schedule

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
  schedule:
    - cron: "*/30 * * * *"

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  issues: write
  packages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/merge-schedule-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

and Description
```txt
test 4

/schedule 2023-09-25T18:59:23.363Z
```

I even got a comment from the action:
<img width="958" alt="image" src="https://github.com/gr2m/merge-schedule-action/assets/3323411/ff859efa-8e44-4853-b95a-9c9b319099a2">

_All the dates I've tried was in the future_

_`permissions` section was needed b/c I was getting the following error_
```
Run gr2m/merge-schedule-action@v2
Handling pull request opened for https://github.com/birkasecorba/<repo-name>/pull/1
Error: HttpError: Resource not accessible by integration
```

### Tests
- Tried with 5 minutes, 15 minutes, 30 minutes, 1hour intervals. In all cases the merge time fell in those intervals and I've waited 2x the interval to make sure.
- Tried `time_zone` with option with `with:` in yaml
- Tried without providing any date `/schedule`
- Tried with @v1
